# Generated by Django 5.0.6 on 2024-11-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttendanceApp', '0002_alter_studentscustomuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentscustomuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
