# Generated by Django 5.0.6 on 2024-11-28 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AttendanceApp', '0003_alter_studentscustomuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentscustomuser',
            name='otp',
        ),
    ]
