# Generated by Django 5.0.6 on 2024-11-29 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AttendanceApp', '0005_alter_studentscustomuser_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecedata',
            old_name='ection',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='itdata',
            old_name='ection',
            new_name='section',
        ),
    ]
