# Generated by Django 5.0.6 on 2024-11-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttendanceApp', '0006_rename_ection_ecedata_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subotp',
            name='location',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
