# Generated by Django 5.0.6 on 2024-12-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttendanceApp', '0007_subotp_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subotp',
            old_name='location',
            new_name='langitude',
        ),
        migrations.AddField(
            model_name='subotp',
            name='londitude',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
