# Generated by Django 5.0.6 on 2024-12-01 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AttendanceApp', '0008_rename_location_subotp_langitude_subotp_londitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csedata',
            name='location',
        ),
        migrations.RemoveField(
            model_name='csedata',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='ecedata',
            name='location',
        ),
        migrations.RemoveField(
            model_name='ecedata',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='itdata',
            name='location',
        ),
        migrations.RemoveField(
            model_name='itdata',
            name='otp',
        ),
    ]
